import React from 'react'
import ReactDOM from 'react-dom/client'
import App from './App.tsx'
import './styles/index.css'

// Register Service Worker for PWA (vite-plugin-pwa auto-generates this)
// SW registration happens automatically via registerSW.js generated by vite-plugin-pwa
// For Phase 4, we'll add advanced offline caching and sync strategies

ReactDOM.createRoot(document.getElementById('root')!).render(
  <React.StrictMode>
    <App />
  </React.StrictMode>
)
